name: trust
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - openssl=3.0.15
  - pip
  - python=3.10.14
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.21.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.6
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bitsandbytes==0.44.0
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.14.7
      - dill==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - einops-exts==0.0.4
      - exceptiongroup==1.2.2
      - fastapi==0.104.1
      - ffmpy==0.4.0
      - filelock==3.16.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.2.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==3.34.0
      - gradio-client==0.7.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.17.3
      - idna==3.10
      - ijson==3.2.3
      - importlib-metadata==6.6.0
      - importlib-resources==6.4.5
      - inflection==0.5.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - latex2mathml==3.77.0
      - linkify-it-py==2.0.3
      - markdown-it-py==2.2.0
      - markdown2==2.4.8
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mmengine==0.10.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.15
      - narwhals==1.8.3
      - natsort==8.4.0
      - networkx==3.3
      - nltk==3.8.1
      - numpy==1.26.2
      - open-clip-torch==2.16.0
      - openai==1.3.7
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.5.5.64
      - orjson==3.9.10
      - packaging==23.2
      - pandas==2.2.3
      - peft==0.12.0
      - pillow==10.1.0
      - platformdirs==4.3.6
      - protobuf==3.20.3
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.10
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.31.0
      - rich==13.8.1
      - rpds-py==0.20.0
      - ruff==0.6.7
      - safetensors==0.4.5
      - scikit-learn==1.2.2
      - scipy==1.14.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.27.0
      - svgwrite==1.4.3
      - sympy==1.13.3
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - timm==0.6.13
      - tokenizers==0.14.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm==4.65.0
      - transformers==4.34.1
      - typer==0.12.5
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - urllib3==2.2.3
      - uvicorn==0.24.0.post1
      - wandb==0.18.1
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - webdataset==0.2.79
      - websockets==11.0.3
      - xxhash==3.5.0
      - yapf==0.40.2
      - yarl==1.12.1
      - zipp==3.20.2
      - git+https://github.com/openai/CLIP.git
